version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 6543:5432
    volumes:
      - mammoth_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

volumes:
  mammoth_db:
